#**Guided Lab 386.3.6 - How to Select Columns in Pandas DataFrames**

---

##**Learning Objective:**
This lab focuses on accessing and selecting specific columns from Pandas DataFrames, a fundamental skill in data manipulation and analysis.

By the end this lab, learners will be able to Select any specified column or columns from Pandas Dataframe.



##**Lab Activities:**

1. **Import Dataset:** Begin by importing the `cars.json` dataset into a Pandas DataFrame named `df_cars`.
2. **Select Single Column:** Extract the 'Car' column to demonstrate single column selection.
3. **Select Multiple Columns:** Select 'Car', 'Model', and 'quantity' columns to illustrate multiple column selection.
4. **Select by Column Index:** Practice selecting columns using their index number.
5. **Continue Learning:** This lab serves as an introduction. Further exploration of column selection techniques will be covered later in the module.

##**Introduction:**


**Viewing Column Names Using Column Attribute**

- Get all column names:
  ```
  df.columns
  ```

- Get a single column name by index position:
  ```
  df.columns[1]
    ```

- Get multiple column names by index positions:
  ```
  df.columns[[0, 3, 4]]
    ```

**Selecting Columns Using Square Brackets `[ ]`**

- To select a **single column**, use square brackets [ ] with the column name:
  ```   
  df['colName']
    ```

- To select **multiple columns**, use a list of column names in the down square bracker:  
  ```
  df[['col1', 'col2']]

  ```

  **Simple Way to Remember**

- df['colName'] → gives you the data

- df.columns[0] → gives you the name

---



---

## **Dataset:**

The lab utilizes the [`cars.json`](https://drive.google.com/file/d/1CXAK8gbuLtc2NNOXVUgmja8fDg0TrNZm/view) dataset, providing a practical context for applying column selection methods.

 Let import cars dataset in Panda dataframe.

In [ ]:
import pandas as pd
df_cars = pd.read_json('cars.json')
df_cars

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin,quantity,city
0,Chevrolet Vega,25.0,4,140.0,75,2542,17.0,74,US,177,NJ
1,Chevrolet Vega (sw),22.0,4,140.0,72,2408,19.0,71,US,91,DALLAS
2,Chevrolet Vega 2300,28.0,4,140.0,90,2264,15.5,71,US,74,TEXAS
3,Chevrolet Woody,24.5,4,98.0,60,2164,22.1,76,US,241,OH
4,Chevrolete Chevelle Malibu,16.0,6,250.0,105,3897,18.5,75,US,206,NewYork
...,...,...,...,...,...,...,...,...,...,...,...
156,Mercury Capri v6,21.0,6,155.0,107,2472,14.0,73,US,158,NewYork
157,Mercury Cougar Brougham,15.0,8,302.0,130,4295,14.9,77,US,27,NJ
158,Mercury Grand Marquis,16.5,8,351.0,138,3955,13.2,79,US,332,DALLAS
159,Mercury Lynx l,36.0,4,98.0,70,2125,17.3,82,US,425,TEXAS
160,Mercury Marquis,11.0,8,429.0,208,4633,11.0,72,US,112,OH

##**Example: View Single Column Name by Index Number**

In [ ]:
df_cars.columns[0]

'Car'

##**Example: View Multiple Column Name by Index Number**

In [ ]:
df_cars.columns[[0,1,9]]

Index(['Car', 'MPG', 'quantity'], dtype='object')

##**Example - Select Single Column Data using Square brackets [ ]:**

Suppose we are interested in the Name of the cars.

In [ ]:
df_cars['Car']

0                  Chevrolet Vega
1             Chevrolet Vega (sw)
2             Chevrolet Vega 2300
3                 Chevrolet Woody
4      Chevrolete Chevelle Malibu
                  ...
156              Mercury Capri v6
157       Mercury Cougar Brougham
158         Mercury Grand Marquis
159                Mercury Lynx l
160               Mercury Marquis
Name: Car, Length: 161, dtype: object

In [ ]:
df_cars[df_cars.columns[0]]

0                  Chevrolet Vega
1             Chevrolet Vega (sw)
2             Chevrolet Vega 2300
3                 Chevrolet Woody
4      Chevrolete Chevelle Malibu
                  ...
156              Mercury Capri v6
157       Mercury Cougar Brougham
158         Mercury Grand Marquis
159                Mercury Lynx l
160               Mercury Marquis
Name: Car, Length: 161, dtype: object

If you notice, both code examples give the same result because:

- `df_cars['Car']`:  
  This directly selects the column named **'Car'** and returns the column data as a **Series**.  
  This is called **direct column access**.

- `df_cars[df_cars.columns[0]]`:  
  This first gets the name of the first column using `df_cars.columns[0]`, which is `'Car'`.  
  It then uses that name to select the same column data.  
  This is called **dynamic column selection by position**.

Since:
`df_cars.columns[0] == 'Car'`

Both statements return the same result.

- `df_cars['Car']` → hardcoded column name  
- `df_cars[df_cars.columns[0]]` → dynamic column selection by position

##**Example: Select Multiple Columns Data by Indexes**

In [ ]:
df_cars[df_cars.columns[[0,1,9]]]

                            Car   MPG  quantity
0                Chevrolet Vega  25.0       177
1           Chevrolet Vega (sw)  22.0        91
2           Chevrolet Vega 2300  28.0        74
3               Chevrolet Woody  24.5       241
4    Chevrolete Chevelle Malibu  16.0       206
..                          ...   ...       ...
156            Mercury Capri v6  21.0       158
157     Mercury Cougar Brougham  15.0        27
158       Mercury Grand Marquis  16.5       332
159              Mercury Lynx l  36.0       425
160             Mercury Marquis  11.0       112

[161 rows x 3 columns]



---

##**Example: Select multiple Columns Data using Square brackets [ ]**

Suppose, we are interested in the cars name, Model of the cars, and quantity

In [ ]:
df_cars[['Car','Model', 'quantity']]

                            Car  Model  quantity
0                Chevrolet Vega     74       177
1           Chevrolet Vega (sw)     71        91
2           Chevrolet Vega 2300     71        74
3               Chevrolet Woody     76       241
4    Chevrolete Chevelle Malibu     75       206
..                          ...    ...       ...
156            Mercury Capri v6     73       158
157     Mercury Cougar Brougham     77        27
158       Mercury Grand Marquis     79       332
159              Mercury Lynx l     82       425
160             Mercury Marquis     72       112

[161 rows x 3 columns]



---

**To be continue: We will continue this lab, later in this Module.**

##**Submission Instructions**
- Submit your completed lab using the Start Assignment button on the assignment page in Canvas.
- Your submission can be include:
  - if you are using notebook then, all tasks should be written and submitted in a single notebook file, for example: (**your_name_labname.ipynb**).
  - if you are using python script file, all tasks should be written and submitted in a single python script file for example: **(your_name_labname.py)**.
- Add appropriate comments and any additional instructions if required.